name: screenshot_callback
description: Flutter plugin that allows you to detect mobile screenshot and execute callback functions on iOS and Android.
version: 3.0.1
homepage: https://github.com/flutter-moum/flutter_screenshot_callback


environment:
  sdk: ">=2.14.0 <=3.4.4"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
  plugin:
    platforms:
      android:
        package: com.flutter.moum.screenshot_callback
        pluginClass: ScreenshotCallbackPlugin
      ios:
        pluginClass: ScreenshotCallbackPlugin
