name: screenshot_callback_example
description: Demonstrates how to use the screenshot_callback plugin.
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  screenshot_callback:
    path: ../

flutter:
  uses-material-design: true