name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.0.2
homepage: https://github.com/anicdh

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bip39: ^1.0.3
  pointycastle: ^3.7.3
  bip32: ^2.0.0
  hex: ^0.2.0
  bs58check: ^1.0.1
  fixnum: ^1.1.0
  meta: ^1.1.6
  bech32: 0.2.2

dev_dependencies:
  test: ^1.15.4
